In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("IMDB Dataset.csv")
data.sample(3)

,review,sentiment
22765,"Sorry folks, I love Ray Bolger's work but the ...",negative
30205,Dear me. Where do I start? The dad isn't anywh...,negative
33118,"An OK flick, set in Mexico, about a hit-man (S...",negative


In [3]:
# checking duplicated in dataset
data.duplicated().sum()

418

In [4]:
# Removing duplicated value from the dataset
data.drop_duplicates(inplace=True)

In [5]:
data.duplicated().sum() # duplicated value are removed form  the datset

0

In [6]:
# checking null value
data.isnull().sum() # No null valued are present

review       0
sentiment    0
dtype: int64

In [7]:
# Checking the data are balanced or imblanced
data["sentiment"].value_counts() # data are balanced

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [8]:
# statical analysic
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49582 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     49582 non-null  object
 1   sentiment  49582 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB


In [9]:
# statical analysic
data.describe()

,review,sentiment
count,49582,49582
unique,49582,2
top,One of the other reviewers has mentioned that ...,positive
freq,1,24884


In [10]:
data.shape

(49582, 2)

# preprocessing

In [11]:
# converting to lower-case
data["review"] = data["review"].str.lower()
data["sentiment"] = data["sentiment"].str.lower()

In [12]:
data.sample(3)

,review,sentiment
29947,"this movie was, perhaps, one of the most unori...",negative
46494,the mood of this movie is pretty good and it c...,negative
30415,mr. moto's gamble has a fairly straight forwar...,negative


In [13]:
# Removing the HTML Tages

import re

def removing_html_tag(text):
    if isinstance(text,str):
        pattern = re.compile("<.*?>")
        return pattern.sub("",text)

    return text

In [14]:
data["review"] = data["review"].apply(removing_html_tag)
data["sentiment"] = data["sentiment"].apply(removing_html_tag)

In [15]:
data.sample(5)

,review,sentiment
48644,motorama viewers should already by keen on oth...,positive
6740,'in the line of fire' tells the story of the g...,positive
10824,"within 15 minutes, my whole family was rooting...",negative
30178,words cannot describe how utterly abysmal this...,negative
9119,"by randolph scott standards of the 1950s, this...",negative


In [16]:
# removing url 

def removing_url(text):
    if isinstance(text,str):
        pattern = re.compile(r"https?://\S+|www\.S+")
        return pattern.sub(r"",text)

    return text

In [17]:
data["review"] = data["review"].apply(removing_url)
data["sentiment"] = data["sentiment"].apply(removing_url)

In [18]:
data.tail(2)

,review,sentiment
49998,i'm going to have to disagree with the previou...,negative
49999,no one expects the star trek movies to be high...,negative


In [19]:
# Removign punctuation from the dataset
import string
pun = string.punctuation

def removing_punctuation(text):
    if isinstance(text,str):
        return text.translate(str.maketrans("","",pun))
    return text

In [20]:
data["review"] = data["review"].apply(removing_punctuation)
data["sentiment"] = data["sentiment"].apply(removing_punctuation)

In [21]:
data.sample(3)

,review,sentiment
13986,too much stock footage almost one third of thi...,negative
30052,this is a truly remarkable piece of cinematic ...,positive
10637,i learned a thing you have to take this film l...,positive


In [22]:
# # spelling correction

# from textblob import TextBlob

# def spelling_corr(text):
#     if isinstance(text,str):
        
#         return str(TextBlob(text).correct())
#     return text

In [23]:
# data["review"] = data["review"].apply(spelling_corr)
# data["sentiment"] = data["sentiment"].apply(spelling_corr)

In [24]:
# data.sample(5)

In [25]:
# Removign Stop words
import nltk
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

def Removign_stop_words(text):
    if isinstance(text,str):
        return " ".join([i for i in text.split() if i not in stop_words])
    return text

In [26]:
data["review"] = data["review"].apply(Removign_stop_words)

In [27]:
data.sample(3)

,review,sentiment
7135,film total bore entrapment way better aspects ...,negative
35177,begin erroneous synopsis xmen origins wolverin...,negative
48527,least teenage geek gets girl films guy usually...,negative


In [28]:
# Tokenization
from nltk.tokenize import sent_tokenize,word_tokenize

def word_token(text):
    if isinstance(text,str):
        return word_tokenize(text) 
    raise ValueError("Input must be string")

def sent_token(text):
    if isinstance(text,str):
        return sent_tokenize(text) 
    raise ValueError("Input must be string")

In [29]:
data["review"] = data["review"].apply(word_token)

In [30]:
data.sample(3)

,review,sentiment
14612,"[video, box, joyride, says, starring, second, ...",negative
40790,"[touching, story, two, families, israel, relat...",positive
23242,"[cause, crap, kind, movie, makes, want, go, sm...",negative


In [31]:
# Stemming
from nltk.stem.porter import PorterStemmer
stems = PorterStemmer()

def stemming(text):
    if isinstance(text,str):
        return text
    else:
        return " ".join([stems.stem(word) for word in text])


In [32]:
stemming(["hi"," i", "am","loving","love","scienceing","cricketing"])

'hi  i am love love scienc cricket'

In [33]:
data["review"] = data["review"].apply(stemming)

In [34]:
data.sample(3)

,review,sentiment
15870,astronaut die space brought back militari base...,negative
31337,love movi daughter 3 12 countri girl heart mov...,positive
26716,im go make short sweet surpris use film stori ...,positive


In [35]:
# applying the labelencoder an target column
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["sentiment"] = le.fit_transform(data["sentiment"])

In [36]:
data.sample(2)

,review,sentiment
34356,watcher fun movi taken serious novel written d...,1
11919,rival report pat morgan ginger roger ted rand ...,0


In [37]:
x = data.iloc[:,:1]
y = data.drop(["review"],axis=1)

In [38]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_trian,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [39]:
print(f"x_trian shape is {x_train.shape} {"\n"} y_trian shape is {y_trian.shape}")
print(f"x_test shape is {x_test.shape} {"\n"} y_test shape is {y_test.shape}")

x_trian shape is (39665, 1) 
 y_trian shape is (39665, 1)
x_test shape is (9917, 1) 
 y_test shape is (9917, 1)


In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,2))

In [41]:
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [42]:
x_train_bow

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
x_train_bow.shape

(39665, 5000)

In [44]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(x_train_bow,y_trian)

C:\Users\Amita\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [45]:
y_pred1 = gnb.predict(x_test_bow)

In [46]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred1)

0.802460421498437

In [47]:
confusion_matrix(y_test,y_pred1)

array([[4176,  763],
       [1196, 3782]], dtype=int64)

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(x_train_bow,y_trian)
y_pred2 = rf.predict(x_test_bow)
accuracy_score(y_test,y_pred2)

C:\Users\Amita\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.8383583745084199

In [51]:
confusion_matrix(y_test,y_pred2)

array([[4131,  808],
       [ 795, 4183]], dtype=int64)

# word2vec

In [52]:
import gensim
from gensim.utils import simple_preprocess
from gensim.models import word2vec,keyedvectors

In [53]:
story = []

for text in data["review"]:
    raw_sent = sent_tokenize(text)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [57]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2
)

In [58]:
model.build_vocab(story)

In [59]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(27287773, 29385505)

In [60]:
len(model.wv.index_to_key)

57725

In [61]:
def document_vector(doc):
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis = 0)

In [63]:
document_vector(data["review"].values[0])

array([ 0.21730763,  0.4366977 ,  0.2808396 , -0.4360543 ,  0.16178305,
       -0.2978064 , -0.40049618, -0.23433702, -0.5835323 , -0.02803676,
       -0.51748705, -0.54023814, -0.46246827,  0.29067943,  0.39295477,
        0.32981607, -0.5231451 , -0.15000604, -0.5174964 , -0.14140287,
       -0.10582573,  0.16295569,  0.07819337, -0.10878132, -0.41051814,
        0.20576523, -0.3758308 , -0.6329174 ,  0.32669622,  0.06784086,
        0.40781426, -0.4243003 , -0.12077844,  0.17304628,  0.25532633,
        0.575567  ,  0.11753024,  0.06378663, -0.70443547, -0.25532272,
        0.2984538 , -0.85216486, -0.4040839 ,  0.32394215,  0.16483893,
        0.3679207 , -0.03729771, -0.4222942 ,  0.47025844,  0.18775223,
        0.17295194, -0.09510645,  0.12127698, -0.0049111 ,  0.02284081,
       -0.16355649, -0.27135384, -0.1505273 , -0.5027492 , -0.08309886,
       -0.08592073,  0.43777823,  0.03239779,  0.12670809, -0.04084753,
       -0.13759804,  0.01022679,  0.01925182, -0.59782916,  0.01

In [67]:
from tqdm import tqdm

In [68]:
x = []

for doc in tqdm(data["review"].values):
    x.append(document_vector(doc))

100%|████████████████████████████████████████████████████████████████████████████| 49582/49582 [34:17<00:00, 24.10it/s]


In [70]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [75]:
mnb = GaussianNB()
mnb.fit(X_train,Y_train)
y_pred_m = mnb.predict(X_test)
accuracy_score(Y_test,y_pred_m)

C:\Users\Amita\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7793687607139256

In [76]:
rf1 = RandomForestClassifier()

rf1.fit(X_train,Y_train)
y_pred_r = rf1.predict(X_test)
accuracy_score(Y_test,y_pred_r)

C:\Users\Amita\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.8400726026015932